// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Account struct {
	Uuid string
	Name string
}

type Setting struct {
	ID       int64
	Width    int64
	Height   int64
	Fontsize int64
}
